export const PERMISSIONS = {
  SERVICE: {
    CREATE: "service:create",
    READ: "service:read",
    UPDATE: "service:update",
    DELETE: "service:delete",
  },
  APPOINTMENT: {
    CREATE: "appointment:create",
    READ: "appointment:read",
    UPDATE: "appointment:update",
    DELETE: "appointment:delete",
  },
  ORGANIZATION: {
    CREATE: "organization:create",
    READ: "organization:read",
    UPDATE: "organization:update",
    DELETE: "organization:delete",
    INVITE_MEMBER: "organization:invite",
    MANAGE_ROLE: "organization:manage-role",
  },
  USER: {
    READ: "user:read",
    UPDATE: "user:update",
    DELETE: "user:delete",
  },
};

export const ROLE_PERMISSIONS: Record<string, string[]> = {
  owner: [
    PERMISSIONS.SERVICE.CREATE,
    PERMISSIONS.SERVICE.READ,
    PERMISSIONS.SERVICE.UPDATE,
    PERMISSIONS.SERVICE.DELETE,
    PERMISSIONS.APPOINTMENT.READ,
    PERMISSIONS.APPOINTMENT.UPDATE,
    PERMISSIONS.APPOINTMENT.DELETE,
    PERMISSIONS.ORGANIZATION.CREATE,
    PERMISSIONS.ORGANIZATION.READ,
    PERMISSIONS.ORGANIZATION.UPDATE,
    PERMISSIONS.ORGANIZATION.DELETE,
    PERMISSIONS.ORGANIZATION.INVITE_MEMBER,
    PERMISSIONS.ORGANIZATION.MANAGE_ROLE,
  ],
  admin: [
    PERMISSIONS.SERVICE.CREATE,
    PERMISSIONS.SERVICE.READ,
    PERMISSIONS.SERVICE.UPDATE,
    PERMISSIONS.SERVICE.DELETE,
    PERMISSIONS.APPOINTMENT.READ,
    PERMISSIONS.APPOINTMENT.UPDATE,
    PERMISSIONS.APPOINTMENT.DELETE,
    PERMISSIONS.ORGANIZATION.READ,
    PERMISSIONS.ORGANIZATION.UPDATE,
    PERMISSIONS.ORGANIZATION.INVITE_MEMBER,
  ],
  member: [
    PERMISSIONS.APPOINTMENT.READ,
    PERMISSIONS.APPOINTMENT.UPDATE,
    PERMISSIONS.ORGANIZATION.READ,
  ],
  customer: [
    PERMISSIONS.APPOINTMENT.CREATE,
    PERMISSIONS.APPOINTMENT.READ,
    PERMISSIONS.SERVICE.READ,
  ],
};
